apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: flaresolverr/flaresolverr:latest
          ports:
            - containerPort: 8191
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  selector:
    app: flaresolverr
  ports:
    - port: 8191
      targetPort: 8191
