//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeBlock) DeepCopyInto(out *BeforeBlock) {
	*out = *in
	if in.PathSelector != nil {
		in, out := &in.PathSelector, &out.PathSelector
		*out = new(SelectorField)
		**out = **in
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeBlock.
func (in *BeforeBlock) DeepCopy() *BeforeBlock {
	if in == nil {
		return nil
	}
	out := new(BeforeBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Caps) DeepCopyInto(out *Caps) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CategoryMappings != nil {
		in, out := &in.CategoryMappings, &out.CategoryMappings
		*out = make([]CategoryMapping, len(*in))
		copy(*out, *in)
	}
	in.Modes.DeepCopyInto(&out.Modes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Caps.
func (in *Caps) DeepCopy() *Caps {
	if in == nil {
		return nil
	}
	out := new(Caps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptchaBlock) DeepCopyInto(out *CaptchaBlock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptchaBlock.
func (in *CaptchaBlock) DeepCopy() *CaptchaBlock {
	if in == nil {
		return nil
	}
	out := new(CaptchaBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoryMapping) DeepCopyInto(out *CategoryMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoryMapping.
func (in *CategoryMapping) DeepCopy() *CategoryMapping {
	if in == nil {
		return nil
	}
	out := new(CategoryMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadBlock) DeepCopyInto(out *DownloadBlock) {
	*out = *in
	if in.Before != nil {
		in, out := &in.Before, &out.Before
		*out = new(BeforeBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]SelectorBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InfoHash != nil {
		in, out := &in.InfoHash, &out.InfoHash
		*out = new(InfoHashBlock)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadBlock.
func (in *DownloadBlock) DeepCopy() *DownloadBlock {
	if in == nil {
		return nil
	}
	out := new(DownloadBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorBlock) DeepCopyInto(out *ErrorBlock) {
	*out = *in
	in.Message.DeepCopyInto(&out.Message)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorBlock.
func (in *ErrorBlock) DeepCopy() *ErrorBlock {
	if in == nil {
		return nil
	}
	out := new(ErrorBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FieldsBlock) DeepCopyInto(out *FieldsBlock) {
	{
		in := &in
		*out = make(FieldsBlock, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldsBlock.
func (in FieldsBlock) DeepCopy() FieldsBlock {
	if in == nil {
		return nil
	}
	out := new(FieldsBlock)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterBlock) DeepCopyInto(out *FilterBlock) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterBlock.
func (in *FilterBlock) DeepCopy() *FilterBlock {
	if in == nil {
		return nil
	}
	out := new(FilterBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Indexer) DeepCopyInto(out *Indexer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Indexer.
func (in *Indexer) DeepCopy() *Indexer {
	if in == nil {
		return nil
	}
	out := new(Indexer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Indexer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerList) DeepCopyInto(out *IndexerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Indexer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerList.
func (in *IndexerList) DeepCopy() *IndexerList {
	if in == nil {
		return nil
	}
	out := new(IndexerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IndexerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerSpec) DeepCopyInto(out *IndexerSpec) {
	*out = *in
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LegacyLinks != nil {
		in, out := &in.LegacyLinks, &out.LegacyLinks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Caps.DeepCopyInto(&out.Caps)
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]SettingsField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Login != nil {
		in, out := &in.Login, &out.Login
		*out = new(Login)
		(*in).DeepCopyInto(*out)
	}
	if in.Search != nil {
		in, out := &in.Search, &out.Search
		*out = new(Search)
		(*in).DeepCopyInto(*out)
	}
	if in.Download != nil {
		in, out := &in.Download, &out.Download
		*out = new(DownloadBlock)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerSpec.
func (in *IndexerSpec) DeepCopy() *IndexerSpec {
	if in == nil {
		return nil
	}
	out := new(IndexerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerStatus) DeepCopyInto(out *IndexerStatus) {
	*out = *in
	if in.LastHealthCheckTime != nil {
		in, out := &in.LastHealthCheckTime, &out.LastHealthCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerStatus.
func (in *IndexerStatus) DeepCopy() *IndexerStatus {
	if in == nil {
		return nil
	}
	out := new(IndexerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfoHashBlock) DeepCopyInto(out *InfoHashBlock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfoHashBlock.
func (in *InfoHashBlock) DeepCopy() *InfoHashBlock {
	if in == nil {
		return nil
	}
	out := new(InfoHashBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Login) DeepCopyInto(out *Login) {
	*out = *in
	if in.Cookies != nil {
		in, out := &in.Cookies, &out.Cookies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Captcha != nil {
		in, out := &in.Captcha, &out.Captcha
		*out = new(CaptchaBlock)
		**out = **in
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SelectorInputs != nil {
		in, out := &in.SelectorInputs, &out.SelectorInputs
		*out = make(map[string]SelectorBlock, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.GetSelectorInputs != nil {
		in, out := &in.GetSelectorInputs, &out.GetSelectorInputs
		*out = make(map[string]SelectorBlock, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = make([]ErrorBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Test != nil {
		in, out := &in.Test, &out.Test
		*out = new(PageTestBlock)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Login.
func (in *Login) DeepCopy() *Login {
	if in == nil {
		return nil
	}
	out := new(Login)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Modes) DeepCopyInto(out *Modes) {
	*out = *in
	if in.Search != nil {
		in, out := &in.Search, &out.Search
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TvSearch != nil {
		in, out := &in.TvSearch, &out.TvSearch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MovieSearch != nil {
		in, out := &in.MovieSearch, &out.MovieSearch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MusicSearch != nil {
		in, out := &in.MusicSearch, &out.MusicSearch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BookSearch != nil {
		in, out := &in.BookSearch, &out.BookSearch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Modes.
func (in *Modes) DeepCopy() *Modes {
	if in == nil {
		return nil
	}
	out := new(Modes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PageTestBlock) DeepCopyInto(out *PageTestBlock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PageTestBlock.
func (in *PageTestBlock) DeepCopy() *PageTestBlock {
	if in == nil {
		return nil
	}
	out := new(PageTestBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseBlock) DeepCopyInto(out *ResponseBlock) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseBlock.
func (in *ResponseBlock) DeepCopy() *ResponseBlock {
	if in == nil {
		return nil
	}
	out := new(ResponseBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowFilterBlock) DeepCopyInto(out *RowFilterBlock) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowFilterBlock.
func (in *RowFilterBlock) DeepCopy() *RowFilterBlock {
	if in == nil {
		return nil
	}
	out := new(RowFilterBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowsBlock) DeepCopyInto(out *RowsBlock) {
	*out = *in
	in.DateHeaders.DeepCopyInto(&out.DateHeaders)
	if in.Case != nil {
		in, out := &in.Case, &out.Case
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]RowFilterBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Count.DeepCopyInto(&out.Count)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowsBlock.
func (in *RowsBlock) DeepCopy() *RowsBlock {
	if in == nil {
		return nil
	}
	out := new(RowsBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Search) DeepCopyInto(out *Search) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]SearchPathBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.KeywordsFilters != nil {
		in, out := &in.KeywordsFilters, &out.KeywordsFilters
		*out = make([]FilterBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = make([]ErrorBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreprocessingFilters != nil {
		in, out := &in.PreprocessingFilters, &out.PreprocessingFilters
		*out = make([]FilterBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Rows.DeepCopyInto(&out.Rows)
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make(FieldsBlock, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Search.
func (in *Search) DeepCopy() *Search {
	if in == nil {
		return nil
	}
	out := new(Search)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchPathBlock) DeepCopyInto(out *SearchPathBlock) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(ResponseBlock)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchPathBlock.
func (in *SearchPathBlock) DeepCopy() *SearchPathBlock {
	if in == nil {
		return nil
	}
	out := new(SearchPathBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectorBlock) DeepCopyInto(out *SelectorBlock) {
	*out = *in
	if in.Case != nil {
		in, out := &in.Case, &out.Case
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]FilterBlock, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectorBlock.
func (in *SelectorBlock) DeepCopy() *SelectorBlock {
	if in == nil {
		return nil
	}
	out := new(SelectorBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectorField) DeepCopyInto(out *SelectorField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectorField.
func (in *SelectorField) DeepCopy() *SelectorField {
	if in == nil {
		return nil
	}
	out := new(SelectorField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsField) DeepCopyInto(out *SettingsField) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsField.
func (in *SettingsField) DeepCopy() *SettingsField {
	if in == nil {
		return nil
	}
	out := new(SettingsField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Torrent) DeepCopyInto(out *Torrent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Torrent.
func (in *Torrent) DeepCopy() *Torrent {
	if in == nil {
		return nil
	}
	out := new(Torrent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Torrent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentList) DeepCopyInto(out *TorrentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Torrent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentList.
func (in *TorrentList) DeepCopy() *TorrentList {
	if in == nil {
		return nil
	}
	out := new(TorrentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorrentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentRequest) DeepCopyInto(out *TorrentRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentRequest.
func (in *TorrentRequest) DeepCopy() *TorrentRequest {
	if in == nil {
		return nil
	}
	out := new(TorrentRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorrentRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentRequestList) DeepCopyInto(out *TorrentRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TorrentRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentRequestList.
func (in *TorrentRequestList) DeepCopy() *TorrentRequestList {
	if in == nil {
		return nil
	}
	out := new(TorrentRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TorrentRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentRequestSpec) DeepCopyInto(out *TorrentRequestSpec) {
	*out = *in
	if in.Indexers != nil {
		in, out := &in.Indexers, &out.Indexers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentRequestSpec.
func (in *TorrentRequestSpec) DeepCopy() *TorrentRequestSpec {
	if in == nil {
		return nil
	}
	out := new(TorrentRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentRequestStatus) DeepCopyInto(out *TorrentRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentRequestStatus.
func (in *TorrentRequestStatus) DeepCopy() *TorrentRequestStatus {
	if in == nil {
		return nil
	}
	out := new(TorrentRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentSpec) DeepCopyInto(out *TorrentSpec) {
	*out = *in
	if in.PublishedAt != nil {
		in, out := &in.PublishedAt, &out.PublishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentSpec.
func (in *TorrentSpec) DeepCopy() *TorrentSpec {
	if in == nil {
		return nil
	}
	out := new(TorrentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorrentStatus) DeepCopyInto(out *TorrentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorrentStatus.
func (in *TorrentStatus) DeepCopy() *TorrentStatus {
	if in == nil {
		return nil
	}
	out := new(TorrentStatus)
	in.DeepCopyInto(out)
	return out
}
