apiVersion: torrents.vitoru.fun/v1alpha1
kind: Indexer
metadata:
  name: internet-archive
spec:
  caps:
    categorymappings:
    - cat: Audio
      desc: audio
      id: audio
    - cat: Audio
      desc: etree
      id: etree
    - cat: Movies
      desc: movies
      id: movies
    - cat: TV
      desc: movies
      id: movies
    - cat: Other/Misc
      desc: image
      id: image
    - cat: Books
      desc: texts
      id: texts
    - cat: PC
      desc: software
      id: software
    - cat: Other
      desc: web
      id: web
    - cat: Other
      desc: collection
      id: collection
    - cat: Other
      desc: account
      id: account
    - cat: Other
      desc: data
      id: data
    - cat: Other
      desc: other
      id: other
    modes:
      search:
      - q
  description: Internet Archive is a non-profit digital library offering free universal
    access to books, movies & music, as well as 406 billion archived web pages
  encoding: UTF-8
  id: internetarchive
  language: en-US
  links:
  - https://archive.org/
  name: Internet Archive
  search:
    fields:
      _btih:
        optional: true
        selector: btih
      _id:
        selector: identifier
      category:
        selector: mediatype
      date:
        selector: publicdate
      details:
        text: details/{{ .Result._id }}
      download:
        text: download/{{ .Result._id }}/{{ .Result._id }}_archive.torrent
      downloadvolumefactor:
        text: "0"
      grabs:
        optional: true
        selector: downloads
      infohash:
        text: '{{ if .Config.noMagnet }}{{ else }}{{ .Result._btih }}{{ end }}'
      leechers:
        text: "1"
      seeders:
        text: "1"
      size:
        selector: item_size
      title:
        default: Missing title for {{ .Result._id }}
        optional: true
        selector: title
      uploadvolumefactor:
        text: "1"
    inputs:
      fl[]: identifier,title,mediatype,item_size,downloads,btih,publicdate
      output: json
      q: '{{ if and .Config.titleOnly .Keywords }}title:({{ else }}{{ end }}{{ if
        .Keywords }}{{ .Keywords }}{{ else }}{{ end }}{{ if and .Config.titleOnly
        .Keywords }}){{ else }}{{ end }}{{ if .Keywords }} AND {{ else }}{{ end }}format:("Archive
        BitTorrent"){{ if .Categories }} AND mediatype:({{ join .Categories " OR "
        }}){{ else }}{{ end }}'
      rows: "100"
      sort: '{{ if .Keywords }}{{ re_replace .Config.type "_" "" }}{{ .Config.sort
        }}{{ else }}-publicdate{{ end }}'
    paths:
    - path: advancedsearch.php
      response:
        type: json
    rows:
      count:
        selector: response.numFound
      dateheaders: {}
      selector: response.docs
  settings:
  - default: "true"
    label: Search only in title
    name: titleOnly
    type: checkbox
  - default: "false"
    label: Download using .torrent only. No Magnets.
    name: noMagnet
    type: checkbox
  - default: publicdate
    label: Sort requested from site
    name: sort
    options:
      downloads: downloads
      item_size: size
      publicdate: created
    type: select
  - default: '-'
    label: Order requested from site
    name: type
    options:
      '-': desc
      _: asc
    type: select
  type: public
