apiVersion: torrents.vitoru.fun/v1alpha1
kind: Indexer
metadata:
  name: zetorrents
spec:
  caps:
    allowrawsearch: true
    categories:
      Other: Other
    modes:
      search:
      - q
  description: zetorrents is a FRENCH Public site for MOVIES / TV / GENERAL
  download:
    selectors:
    - attribute: href
      selector: a[href^="magnet:?"]
  encoding: UTF-8
  id: zetorrents
  language: fr-FR
  legacylinks:
  - https://www.rantop.org/
  - https://www.site-torrent.cc/
  - https://www.torrent-site.com/
  - https://www.protege-torrent.com/
  - https://www.torrent.ws/
  - https://www.protege-liens.com/
  - https://www.protege-liens.net/
  - https://www.torrent.onl/
  - https://www.site-torrent.com/
  - https://www.rantop.my/
  - https://www.zetorrents.in/
  - https://www.zetorrents.vg/
  - https://www.zetorrents.vc/
  - https://www.zetorrents.sk/
  - https://www.zetorrents.my/
  - https://wvw-zetorrents.com/
  - https://www-zetorrents.com/
  - https://www.zetorrents1.com/
  - https://www.zetorrents.diy/
  - https://www.zetorrents2.com/
  - https://www.zetorrents.town/
  - https://zetorrents-proxy.site/
  - https://ww1-zetorrents.me/
  - https://www.zetorrents.rent/
  - https://ww1-zetorrents.town/
  links:
  - https://www.world-torrent.com/
  name: zetorrents
  search:
    fields:
      category:
        text: Other
      date:
        text: now
      details:
        attribute: href
        selector: a[href^="/detail/"]
      download:
        attribute: href
        selector: a[href^="/detail/"]
      downloadvolumefactor:
        text: "0"
      leechers:
        selector: td:nth-child(4)
      seeders:
        selector: td:nth-child(3)
      size:
        selector: td:nth-child(2)
      title:
        text: '{{ if .Config.multilang }}{{ .Result.title_multilang }}{{ else }}{{
          .Result.title_phase2 }}{{ end }}'
      title_multilang:
        filters:
        - args:
          - (?i)\b(MULTI(?!.*(?:FRENCH|ENGLISH|VOSTFR)))\b
          - '{{ .Config.multilanguage }}'
          name: re_replace
        text: '{{ .Result.title_phase2 }}'
      title_phase1:
        filters:
        - args:
          - WEBRIP
          - WEBDL
          name: replace
        - args:
          - (?i)\b(FRENCH|MULTI|TRUEFRENCH|VOSTFR|SUBFRENCH)\b(.+?)(\b((19|20)\d{2})\b)$
          - $3 $1$2
          name: re_replace
        selector: a[href^="/detail/"]
      title_phase2:
        text: '{{ if .Config.vostfr }}{{ .Result.title_vostfr }}{{ else }}{{ .Result.title_phase1
          }}{{ end }}'
      title_vostfr:
        filters:
        - args:
          - (?i)\b(vostfr|subfrench)\b
          - ENGLISH
          name: re_replace
        text: '{{ .Result.title_phase1 }}'
      uploadvolumefactor:
        text: "1"
    keywordsfilters:
    - args:
      - (?i)(S0)(\d{1,2})$
      - saison $2
      name: re_replace
    - args:
      - (?i)(S)(\d{1,3})$
      - saison $2
      name: re_replace
    paths:
    - path: '{{ if .Keywords }}recherche/{{ .Keywords }}{{ else }}home{{ end }}'
    rows:
      count: {}
      dateheaders: {}
      selector: table.table > tbody > tr:has(a[href^="/detail/"])
  settings:
  - name: info_category_8000
    type: info_category_8000
  - default: "false"
    label: Replace MULTi by another language in release name
    name: multilang
    type: checkbox
  - default: FRENCH
    label: Replace MULTi by this language
    name: multilanguage
    options:
      ENGLISH: ENGLISH
      FRENCH: FRENCH
      MULTi ENGLISH: MULTi ENGLISH
      MULTi FRENCH: MULTi FRENCH
      MULTi VOSTFR: MULTi VOSTFR
      VOSTFR: VOSTFR
    type: select
  - default: "false"
    label: Replace VOSTFR and SUBFRENCH with ENGLISH
    name: vostfr
    type: checkbox
  type: public
